{pkgs}: {
  deps = [
    pkgs.pciutils
    pkgs.gtk3
    pkgs.glib
    pkgs.libxkbcommon
    pkgs.mesa
    pkgs.alsa-lib
    pkgs.pango
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.libdrm
    pkgs.at-spi2-atk
    pkgs.dbus
    pkgs.cups
    pkgs.expat
    pkgs.nss
    pkgs.nspr
    pkgs.cairo
    pkgs.x265
    pkgs.nasm
    pkgs.libde265
    pkgs.libaom
    pkgs.libheif
    pkgs.wget
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.glibcLocales
  ];
}
